const DATA={
 alphabet:{name:"Alphabet",icon:"🔤",items:"ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("").map(x=>({label:x,speak:x,image:`images/alphabet/${x.toLowerCase()}.png`}))},
 numbers:{name:"Numbers",icon:"🔢",items:Array.from({length:101},(_,i)=>({label:String(i),speak:numberWord(i),hi:numberHindi(i),image:`images/numbers/${i}.png`}))},
 animals:{name:"Animals",icon:"🐾",items:[
 ["Lion","शेर"],["Tiger","बाघ"],["Elephant","हाथी"],["Giraffe","जिराफ़"],["Zebra","ज़ेब्रा"],["Monkey","बंदर"],["Dog","कुत्ता"],["Cat","बिल्ली"],["Cow","गाय"],["Horse","घोड़ा"],["Goat","बकरी"],["Sheep","भेड़"],["Rabbit","खरगोश"],["Deer","हिरण"],["Bear","भालू"],["Fox","लोमड़ी"],["Wolf","भेड़िया"],["Camel","ऊंट"],["Rhinoceros","गैंडा"],["Hippopotamus","दरियाई घोड़ा"],["Crocodile","मगरमच्छ"],["Panda","पांडा"],["Kangaroo","कंगारू"],["Monkey","बंदर"]
 ].map(([label,hi])=>({label,hi,speak:label,image:`images/animals/${slug(label)}.jpg`}))},
 birds:{name:"Birds",icon:"🐦",items:[
 ["Peacock","मोर"],["Parrot","तोता"],["Sparrow","गौरैया"],["Crow","कौआ"],["Pigeon","कबूतर"],["Eagle","गरुड़"],["Owl","उल्लू"],["Swan","हंस"],["Duck","बत्तख"],["Hen","मुर्गी"],["Rooster","मुर्गा"],["Kingfisher","रामचिरैया"],["Woodpecker","कठफोड़वा"],["Cuckoo","कोयल"],["Flamingo","राजहंस"],["Partridge","तीतर"],["Myna","मैना"],["Heron","बगुला"],["Vulture","गिद्ध"],["Crane","सारस"],["Bulbul","बुलबुल"],["Koel","कोयल"]
 ].map(([label,hi])=>({label,hi,speak:label,image:`images/birds/${slug(label)}.jpg`}))},
 fruits:{name:"Fruits",icon:"🍎",items:[
 ["Apple","सेब"],["Banana","केला"],["Mango","आम"],["Orange","संतरा"],["Grapes","अंगूर"],["Pomegranate","अनार"],["Guava","अमरूद"],["Papaya","पपीता"],["Watermelon","तरबूज"],["Muskmelon","खरबूजा"],["Pineapple","अनानास"],["Coconut","नारियल"],["Papaya","पपीता"],["Litchi","लीची"],["Jackfruit","कटहल"],["Custard Apple","सीताफल"],["Pear","नाशपाती"],["Strawberry","स्ट्रॉबेरी"],["Lemon","नींबू"],["Kiwi","कीवी"],["Peach","आड़ू"],["Plum","आलूबुखारा"],["Chikoo","चीकू"]
 ].map(([label,hi])=>({label,hi,speak:label,image:`images/fruits/${slug(label)}.jpg`}))},
 vegetables:{name:"Vegetables",icon:"🥕",items:[
 ["Potato","आलू"],["Tomato","टमाटर"],["Onion","प्याज़"],["Carrot","गाजर"],["Cabbage","पत्तागोभी"],["Cauliflower","फूलगोभी"],["Spinach","पालक"],["Brinjal","बैंगन"],["Okra","भिंडी"],["Peas","मटर"],["Pumpkin","कद्दू"],["Bottle Gourd","लौकी"],["Bitter Gourd","करेला"],["Cucumber","खीरा"],["Capsicum","शिमला मिर्च"],["Radish","मूली"],["Beetroot","चुकंदर"],["Corn","मक्का"],["Garlic","लहसुन"],["Ginger","अदरक"],["Green Beans","हरी फली"],["Drumstick","सहजन"]
 ].map(([label,hi])=>({label,hi,speak:label,image:`images/vegetables/${slug(label)}.jpg`}))},
 colors:{name:"Colors",icon:"🎨",items:[["Red","लाल"],["Blue","नीला"],["Green","हरा"],["Yellow","पीला"],["Orange","नारंगी"],["Purple","बैंगनी"],["Pink","गुलाबी"],["Brown","भूरा"],["Black","काला"],["White","सफेद"],["Grey","स्लेटी"],["Gold","सुनहरा"],["Silver","चांदी"]].map(([label,hi])=>({label,hi,speak:label,image:`images/colors/${slug(label)}.jpg`}))},
 shapes:{name:"Shapes",icon:"🔷",items:[["Circle","वृत्त"],["Square","वर्ग"],["Triangle","त्रिभुज"],["Rectangle","आयत"],["Oval","अंडाकार"],["Star","तारा"],["Heart","दिल"],["Diamond","हीरा"],["Pentagon","पंचभुज"],["Hexagon","षट्भुज"]].map(([label,hi])=>({label,hi,speak:label,image:`images/shapes/${slug(label)}.jpg`}))},
 countries:{name:"Countries",icon:"🌍",items:[["India","भारत"],["United States","अमेरिका"],["United Kingdom","यूनाइटेड किंगडम"],["Japan","जापान"],["France","फ्रांस"],["Germany","जर्मनी"],["Brazil","ब्राज़ील"],["China","चीन"],["Australia","ऑस्ट्रेलिया"],["Canada","कनाडा"],["Italy","इटली"],["Spain","स्पेन"],["Russia","रूस"],["South Africa","दक्षिण अफ्रीका"],["UAE","संयुक्त अरब अमीरात"],["Nepal","नेपाल"],["Bhutan","भूटान"],["Bangladesh","बांग्लादेश"],["Sri Lanka","श्रीलंका"],["Singapore","सिंगापुर"],["Thailand","थाईलैंड"],["Malaysia","मलेशिया"],["Indonesia","इंडोनेशिया"],["South Korea","दक्षिण कोरिया"]].map(([label,hi])=>({label,hi,speak:label,image:`images/countries/${slug(label)}.jpg`}))},
 india:{name:"India",icon:"🇮🇳",items:[["India Gate","इंडिया गेट"],["Taj Mahal","ताज महल"],["Red Fort","लाल किला"],["Gateway of India","गेटवे ऑफ इंडिया"],["Lotus Temple","लोटस टेंपल"],["Qutub Minar","कुतुब मीनार"],["Charminar","चारमीनार"],["Hawa Mahal","हवा महल"],["India Flag","भारत का झंडा"],["Indian Elephant","भारतीय हाथी"]].map(([label,hi])=>({label,hi,speak:label,image:`images/india/${slug(label)}.jpg`}))},
 personalities:{name:"Famous Indians",icon:"⭐",items:[["A.P.J. Abdul Kalam","ए. पी. जे. अब्दुल कलाम"],["Mahatma Gandhi","महात्मा गांधी"],["Bhagat Singh","भगत सिंह"],["Subhas Chandra Bose","सुभाष चंद्र बोस"],["Rani Lakshmibai","रानी लक्ष्मीबाई"],["Sardar Vallabhbhai Patel","सरदार वल्लभभाई पटेल"],["C.V. Raman","सी. वी. रमन"],["Rabindranath Tagore","रवींद्रनाथ टैगोर"],["Kalpana Chawla","कल्पना चावला"],["Homi J. Bhabha","होमी जे. भाभा"],["Vikram Sarabhai","विक्रम साराभाई"],["Srinivasa Ramanujan","श्रीनिवास रामानुजन"]].map(([label,hi])=>({label,hi,speak:label,image:`images/personalities/${slug(label)}.jpg`}))}
};

function slug(s){return s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function numberWord(n){const a=["zero","one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve","thirteen","fourteen","fifteen","sixteen","seventeen","eighteen","nineteen"];if(n<20)return a[n];if(n<100){let t=["","","twenty","thirty","forty","fifty","sixty","seventy","eighty","ninety"];return t[Math.floor(n/10)]+(n%10?"-"+a[n%10]:"")}return"one hundred"}
function numberHindi(n){const a=["शून्य","एक","दो","तीन","चार","पांच","छह","सात","आठ","नौ","दस","ग्यारह","बारह","तेरह","चौदह","पंद्रह","सोलह","सत्रह","अठारह","उन्नीस","बीस","इक्कीस","बाईस","तेईस","चौबीस","पच्चीस","छब्बीस","सत्ताईस","अट्ठाईस","उनतीस","तीस","इकतीस","बत्तीस","तैंतीस","चौंतीस","पैंतीस","छत्तीस","सैंतीस","अड़तीस","उनतालीस","चालीस","इकतालीस","बयालीस","तैंतालीस","चवालीस","पैंतालीस","छियालीस","सैंतालीस","अड़तालीस","उनचास","पचास","इक्यावन","बावन","तिरेपन","चौवन","पचपन","छप्पन","सत्तावन","अट्ठावन","उनसठ","साठ","इकसठ","बासठ","तिरसठ","चौंसठ","पैंसठ","छियासठ","सड़सठ","अड़सठ","उनहत्तर","सत्तर","इकहत्तर","बहत्तर","तिहत्तर","चौहत्तर","पचहत्तर","छिहत्तर","सतहत्तर","अठहत्तर","उन्यासी","अस्सी","इक्यासी","बयासी","तिरासी","चौरासी","पचासी","छियासी","सत्तासी","अट्ठासी","नवासी","नब्बे","इक्यानवे","बानवे","तिरानवे","चौरानवे","पचानवे","छियानवे","सत्तानवे","अट्ठानवे","निन्यानवे","एक सौ"];return a[n]||""}

let stars=Number(localStorage.getItem("ll_stars")||0), quizzes=Number(localStorage.getItem("ll_quizzes")||0), learned=Number(localStorage.getItem("ll_learned")||0);
let currentCatKey="alphabet",currentIndex=0,quizPool=[],quizIndex=0,quizScore=0,quizAnswered=false,currentQuizAnswer=null;

function save(){localStorage.setItem("ll_stars",stars);localStorage.setItem("ll_quizzes",quizzes);localStorage.setItem("ll_learned",learned);document.getElementById("starCount").textContent=stars}
function showScreen(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");window.scrollTo({top:0,behavior:"smooth"});document.querySelectorAll(".bottom-nav button").forEach(x=>x.classList.remove("active"))}
function goHome(){showScreen("home");document.querySelector(".bottom-nav button").classList.add("active")}
function buildHome(){const grid=document.getElementById("catGrid");grid.innerHTML="";Object.entries(DATA).forEach(([key,cat])=>{const el=document.createElement("button");el.className="cat-card";el.innerHTML=`<div class="cat-icon">${cat.icon}</div><h3>${cat.name}</h3><p>${cat.items.length} learning cards</p><span class="arrow">→</span>`;el.onclick=()=>openCategory(key);grid.appendChild(el)})}
function showAllCategories(){buildHome();toast("All learning worlds are ready to explore.")}
function openCategory(key){currentCatKey=key;currentIndex=0;showScreen("learn");renderLearn()}
function continueLearning(){showScreen("learn");renderLearn()}
function renderLearn(){const cat=DATA[currentCatKey],item=cat.items[currentIndex];document.getElementById("learnCatTitle").textContent=cat.name.toUpperCase();document.getElementById("lessonCounter").textContent=`${currentIndex+1} / ${cat.items.length}`;document.getElementById("wordLabel").textContent=item.speak||item.label;document.getElementById("wordLabelHi").textContent=item.hi||"";const stage=document.getElementById("imageStage"),img=document.getElementById("lessonImage"),fallback=document.getElementById("imageFallbackText");stage.classList.remove("no-image");fallback.textContent=item.label.length>4?item.label.slice(0,1):item.label;img.src=item.image;img.alt=item.label;document.getElementById("progressDots").innerHTML=cat.items.slice(0,Math.min(cat.items.length,30)).map((_,i)=>`<span class="dot ${i<=currentIndex?'done':''}"></span>`).join("");learned++;save();speakCurrent()}
function imageFallback(img){img.closest(".image-stage").classList.add("no-image")}
function nextItem(){currentIndex=(currentIndex+1)%DATA[currentCatKey].items.length;renderLearn()}
function prevItem(){currentIndex=(currentIndex-1+DATA[currentCatKey].items.length)%DATA[currentCatKey].items.length;renderLearn()}
function speakOne(text,lang){if(!("speechSynthesis"in window))return;try{const u=new SpeechSynthesisUtterance(text);u.lang=lang;u.rate=.82;u.pitch=1.05;speechSynthesis.speak(u)}catch(e){}}
function speakCurrent(){speechSynthesis?.cancel();const x=DATA[currentCatKey].items[currentIndex];speakOne(x.speak||x.label,"en-IN");if(x.hi)setTimeout(()=>speakOne(x.hi,"hi-IN"),700)}
function startRandomQuiz(){const keys=Object.keys(DATA);currentCatKey=keys[Math.floor(Math.random()*keys.length)];startQuiz()}
function startQuiz(){const cat=DATA[currentCatKey];quizPool=shuffle(cat.items).slice(0,Math.min(6,cat.items.length));quizIndex=0;quizScore=0;showScreen("quiz");document.getElementById("quizCatLabel").textContent=cat.name.toUpperCase()+" QUIZ";renderQuizQuestion()}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function renderQuizQuestion(){quizAnswered=false;const cat=DATA[currentCatKey],answer=quizPool[quizIndex];currentQuizAnswer=answer;const options=shuffle([answer,...shuffle(cat.items.filter(x=>x.label!==answer.label)).slice(0,3)]);document.getElementById("quizQuestion").innerHTML=`Which one is <b>${answer.speak||answer.label}</b>? ${answer.hi?`<span style="display:block;color:var(--gold2);font:500 14px 'Noto Sans Devanagari'">इनमें से ${answer.hi} कौन सा है?</span>`:""}`;document.getElementById("scoreText").textContent=`Question ${quizIndex+1} of ${quizPool.length}`;document.getElementById("quizLiveScore").textContent=quizScore;document.getElementById("nextBtn").style.display="none";const grid=document.getElementById("quizGrid");grid.innerHTML="";options.forEach(opt=>{const el=document.createElement("button");el.className="quiz-opt";el.innerHTML=`<img src="${opt.image}" alt="" onerror="this.style.display='none';this.nextElementSibling.style.display='block'"><span class="fallback" style="display:none">${opt.label.slice(0,2)}</span><span class="opt-label">${opt.speak||opt.label}</span>${opt.hi?`<span class="hi">${opt.hi}</span>`:""}`;el.onclick=()=>selectAnswer(el,opt,answer);grid.appendChild(el)});setTimeout(()=>speakOne(`Which one is ${answer.speak||answer.label}?`,"en-IN"),200)}
function replayQuestion(){if(currentQuizAnswer)speakOne(`Which one is ${currentQuizAnswer.speak||currentQuizAnswer.label}?`,"en-IN")}
function selectAnswer(el,opt,answer){if(quizAnswered)return;quizAnswered=true;document.querySelectorAll(".quiz-opt").forEach(x=>x.style.pointerEvents="none");if(opt.label===answer.label){el.classList.add("correct");quizScore++;stars++;toast("Correct! +1 star");speakOne("Correct! Great job!","en-IN")}else{el.classList.add("wrong");document.querySelectorAll(".quiz-opt").forEach(x=>{if(x.querySelector(".opt-label").textContent===answer.label||x.querySelector(".opt-label").textContent===answer.speak)x.classList.add("correct")});toast("Good try! Keep learning.");speakOne(`Not quite. It's ${answer.speak||answer.label}.`,"en-IN")}document.getElementById("quizLiveScore").textContent=quizScore;document.getElementById("nextBtn").style.display="inline-block";save()}
function nextQuestion(){quizIndex++;if(quizIndex>=quizPool.length)finishQuiz();else renderQuizQuestion()}
function finishQuiz(){quizzes++;stars+=0;save();showScreen("done");document.getElementById("doneTitle").textContent=quizScore===quizPool.length?"Perfect score!":"Well done!";document.getElementById("doneText").textContent=`You got ${quizScore} out of ${quizPool.length} correct.`;document.getElementById("resultStars").textContent="★".repeat(quizScore)+"☆".repeat(quizPool.length-quizScore)}
function showProgress(){showScreen("progress");document.getElementById("statStars").textContent=stars;document.getElementById("statQuizzes").textContent=quizzes;document.getElementById("statLearned").textContent=learned;document.getElementById("achievementProgress").textContent=Math.min(100,Math.round(stars/50*100))+"%"}
function toast(msg){const t=document.getElementById("toast");t.textContent=msg;t.classList.add("show");clearTimeout(window._toast);window._toast=setTimeout(()=>t.classList.remove("show"),1800)}
buildHome();save();
